sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hTNQ9NnMjcnNMk5byp2ea/Se1UD+dboWXLte5aAEztoXZ5IyKWPI8WBpZI9fdX67Uf78iKKUr7UzIv7JkORTOxul0tQJ22dQnVQvESNkmbUFfPnFyJ5+8S6M1zL8gsRu8FTKAuD2a5IFR9CAB0hGG2LijLyoz9LLBrzvTXYqTFdKRMIJyoH9p7xE3+qa96kqYYqzbzWftmy+Z/zdIhKBPee2lgwxwXRLOgIob1Nthe+27tvDbThBKa2Jk8WVon9MhR8pT4HL/JSc6orKfdqwyi5PGa5iLUGfwk+7ip6Tfg/Js6o8l+Ej7xsNgwz63YywKB852J2uBxq77idvWHyGlzi5P/K8ywqe3xAlT/C77HmgmzC8iXAAmOigu5Ymf2/ZtqgbFgiNqjdl0fOp1WBIFelP0pNSsfzOUvLGt4ZMzc8YZA/HTl2dKd1eAgkfDUOUXLwIF/Ps3rWn6JlqEdI41GtSQ8g7HGWzXQD6b9OFQl+vOt4JiWZJ5S5rF/bgjozEoZXsi9hItzsQpCQ3ULKrpF2qz2l6ttkh98c4vVHM7oZWOBmqeRGkjVUBS+Cm5kYYie983zfTqmO2PU5zFtPZR9X5DaSa4WVuF9boI/PM20iN4Hs1tV4CMI4hAidR4Fxdo3tqWy1fdoZjtUn+FDdtDiPtlE1Mf70iazgjp5XIaLU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/What-s-Mine-s-Mine---Complete_5969
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy